#!/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7
#BMI = ( weight in kg divided by height in meters squared)
#Imperial version: BMI * 703
def gather_info():
    height = float(input("what is your height?"))
    weight = float(input("what is your weight?"))
    system = input("what is your measurement system?").lower().strip()
    return (height, weight, system)

def calculate_bmi(weight,height,system='metric'):
    """
    Return the Boday Mass Index(BMI) for the given
    weight, height and measurement system either
    imperial or metric
    """
    if system == 'metric':
        bmi = weight/(height**2)
    else:
        bmi = 703*(weight/height**2)
    return bmi

while True:
    height, weight,system = gather_info()
    if system.startswith('i'):
        bmi = calculate_bmi(weight, height, system)
        print(f"your BMI is {bmi}")
        break
    elif system.startswith('m'):
        bmi = calculate_bmi(weight, height)
        print(f"Your BMI is {bmi}")
        break
    elif system.startswith(""):
        bmi = calculate_bmi(weight, height)
        print(f"Your BMI is {bmi}")
    else:
        print("Error: Unknown measurement system")



